[font]
normal = { family = "JetBrainsMono Nerd Font Propo", style = "Regular" }
size = 10

[window]
padding = { x = 0, y = 0 }
dynamic_padding = true

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
