import = ["~/.config/alacritty/everforest.toml"]

[font]
normal = { family = "JetBrainsMono Nerd Font Propo", style = "Regular" }
size = 8.5

[window]
padding = { x = 0, y = 0 }
dynamic_padding = true

[colors]
cursor = {cursor = "0xd3c6aa", text = "0x232a2e"}
vi_mode_cursor = {cursor = "0xd3c6aa", text = "0x232a2e"}

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
