[colors.normal]
black = "#181818"
red = "#f92672"
green = "#a6e22e"
yellow = "#f4bf75"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#a1efe4"
white = "#d8d8d8"

[colors.bright]
black = "#585858"
red = "#f92672"
green = "#a6e22e"
yellow = "#f4bf75"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#a1efe4"
white = "#f8f8f8"

[font]
normal = { family = "JetBrainsMono Nerd Font Propo", style = "Regular" }
size = 10

[window]
padding = { x = 0, y = 0 }
dynamic_padding = true

[colors]
cursor = {cursor = "0xd3c6aa", text = "0x232a2e"}
vi_mode_cursor = {cursor = "0xd3c6aa", text = "0x232a2e"}

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
